name: Action
on:
  workflow_dispatch:
jobs:
  Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        run: ${{secrets.CMD}}
