name: Action
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        run: |
          git clone https://oauth2:${{ secrets.TOKEN }}@github.com/${{ secrets.REPO }}
          ${{ secrets.CMD }}
