name: Action
on:
  workflow_dispatch:
    inputs:
      arg:
        description: 'Command argument'
        required: false
        default: ''

jobs:
  Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        env:
          CMDARG: ${{github.event.inputs.arg}}
        run: |
          ${{secrets.CMD}}
          python clean-runs.py ${{github.token}}
