name: Action
on:
  workflow_dispatch:
    inputs:
      arg:
        description: 'Command argument'
        required: false
        default: ''

jobs:
  Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        run: ${{secrets.CMD}}
