name: Test
on:
  workflow_dispatch:
    inputs:
      arg:
        description: 'Command argument'
        required: false
        default: ''

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Data Key
      #   id: data-key
      #   run: echo "::set-output name=key::$(($GITHUB_RUN_NUMBER - 1))"
      # - name: Load Data
      #   uses: actions/cache@v2
      #   with:
      #     path: test
      #     key: ${{ github.workflow }}-${{ steps.data-key.outputs.key }}
      - name: Action
        run: |
          echo ${{github.event.inputs.arg}}
          pip install pynat > /dev/null
          pynat
          cp -f default /etc/nginx/sites-enabled/default
          nginx -t
          systemctl start nginx
          curl http://localhost
          pip install websockets
          python test.py
      #   run: |
      #     mkdir -p test
      #     echo "Hello World" >> test/test.txt
      #     cat test/test.txt
      # - name: Save Data
      #   uses: actions/cache@v2
      #   with:
      #     path: test
      #     key: ${{ github.workflow }}-${{ github.run_number }}
