name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: test
          key: ${{ GITHUB_WORKFLOW }}-${{ GITHUB_RUN_NUMBER }}
      - name: Action
        run: |
          pip install pynat
          pynat
          mkdir -p test
          echo "Hello World" >> test/test.txt
          cat test/test.txt
          # pip install websockets
          # python test.py