name: Test
on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Data Key
        id: data-key
        run: echo "::set-output name=key::$(($GITHUB_RUN_NUMBER - 1))"
      - name: Load Data
        uses: actions/cache@v2
        with:
          path: test
          key: ${{ github.workflow }}-${{ steps.data-key.outputs.key }}
      - name: Action
        run: |
          pip install pynat
          pynat
          mkdir -p test
          echo "Hello World" >> test/test.txt
          cat test/test.txt
          # pip install websockets
          # python test.py
      - name: Save Data
        uses: actions/cache@v2
        with:
          path: test
          key: ${{ github.workflow }}-${{ github.run_number }}
