name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        run: |
          pip install pynat
          pynat
          df -h
          pwd
          ls /mnt
          # pip install websockets
          # python test.py