name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        run: |
          pip install pynat
          pynat
          sudo ping6 ssh.lonedark.com
          sudo apt-get install iperf3
          sudo iperf3 -c ssh.lonedark.com -p 80 -6