name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        run: |
          pip install pynat
          pynat
          sudo apt-get install iperf3
          sudo iperf3 -c 2a02:0180:0006:0001:0000:0000:0000:4c35 -p 80 -6