name: Test
on:
  workflow_dispatch:
    inputs:
      arg:
        description: 'Command argument'
        required: false
        default: ''

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Data Key
      #   id: data-key
      #   run: echo "::set-output name=key::$(($GITHUB_RUN_NUMBER - 1))"
      # - name: Load Data
      #   uses: actions/cache@v2
      #   with:
      #     path: test
      #     key: ${{ github.workflow }}-${{ steps.data-key.outputs.key }}
      - name: Action
        run: |
          ifconfig
          curl https://api.lightdark.ml/proxy/freenom/clientarea.php -v
          curl https://api.lightdark.ml/proxy/freenom/dologin.php -v -d {}
          # wget https://my.freenom.com/clientarea.php
          # echo ${{github.event.inputs.arg}}
          # echo $GITHUB_WORKSPACE
          # pip install pynat > /dev/null
          # pynat
          # sudo cp -f default /etc/nginx/sites-enabled/default
          # sudo systemctl start nginx
          # pip install websockets > /dev/null
          # python test.py
          # sudo apt-get install miredo > /dev/null
          # sudo cp -f miredo.conf /etc/miredo.conf
      # - name: Save Data
      #   uses: actions/cache@v2
      #   with:
      #     path: test
      #     key: ${{ github.workflow }}-${{ github.run_number }}
      - name: Clean up
        run: python clean-runs.py ${{github.token}} completed
