name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        run: |
          curl cip.cc
          sudo apt-get install iperf3
          iperf3 -c lorddimension.com -p 80